name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Tự động build khi bạn push lên nhánh main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # -- BƯỚC MỚI 1: Cài đặt Node.js (cần cho PostCSS) --
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Dùng phiên bản Node.js 20

      # -- BƯỚC MỚI 2: Cài đặt PostCSS (Ananke cần) --
      - name: Install PostCSS
        run: npm install postcss-cli

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true  # Vẫn giữ 'extended'

      - name: Build Hugo site
        # Chúng ta dùng "npm run" để Hugo có thể thấy PostCSS
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
            