name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Tự động build khi bạn push lên nhánh main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # SỬA 1: Thêm 'submodules: true' để tải theme
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true  # Rất quan trọng!

      # SỬA 2: Cài đặt Node.js (cần cho PostCSS)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # SỬA 3: Cài đặt PostCSS và Autoprefixer (theme Ananke cần)
      - name: Install PostCSS Dependencies
        run: npm install -D postcss-cli autoprefixer

      # SỬA 4: Vẫn giữ Hugo Extended
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public